"""Slack notifications, webhook alerts, and feedback channels for redoxquant."""

from __future__ import annotations

import json
import os
import urllib.request
import urllib.error
from typing import Any, Dict, List, Optional


import pandas as pd

from . import schema


def send_slack_alert(
    webhook_url: Optional[str] = None,
    *,
    title: str = "Amperia Assay Run Notification",
    message: Optional[str] = None,
    df: Optional[pd.DataFrame] = None,
    curve: Optional[Any] = None,
    channel: Optional[str] = None,
) -> bool:
    """Send a structured Slack notification with optional assay run metrics.

    Parameters
    ----------
    webhook_url:
        Slack Incoming Webhook URL. If omitted, checks the ``REDOXQUANT_SLACK_WEBHOOK``
        or ``SLACK_WEBHOOK_URL`` environment variables.

    title:
        Header text for the Slack notification card.
    message:
        Optional text message or operator notes.
    df:
        Canonical measurements DataFrame to extract sample metrics.
    curve:
        Fitted calibration curve to display R^2 and 5PL parameters.
    channel:
        Optional Slack channel override.

    Returns
    -------
    bool
        True if the notification was delivered successfully (HTTP 200).
    """
    blocks: List[Dict[str, Any]] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": title, "emoji": True},
        }
    ]

    if message:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": message},
        })

    fields: List[Dict[str, str]] = []

    if curve is not None:
        model_name = getattr(curve, "model", "5PL")
        r2 = getattr(curve, "r_squared", 1.0)
        orient = "Descending" if getattr(curve, "descending", True) else "Ascending"
        fields.append({"type": "mrkdwn", "text": f"*Curve Model:*\n{model_name} ({orient})"})
        fields.append({"type": "mrkdwn", "text": f"*Goodness of Fit:*\nR² = {r2:.4f}"})

    if df is not None:
        total_probes = len(df)
        tags = [str(t) for t in df[schema.TAG].dropna().unique()]
        tags_str = ", ".join(tags) if tags else "None"
        fields.append({"type": "mrkdwn", "text": f"*Total Probes:*\n{total_probes} readings"})
        fields.append({"type": "mrkdwn", "text": f"*Sample Tags:*\n`{tags_str}`"})

    if fields:
        blocks.append({
            "type": "section",
            "fields": fields,
        })

    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "Generated by *<https://github.com/lynchaos/redoxquant|redoxquant>* | Support: `support@yaylali.uk`",
            }
        ],
    })

    payload: Dict[str, Any] = {"blocks": blocks}
    url = webhook_url or os.environ.get("REDOXQUANT_SLACK_WEBHOOK") or os.environ.get("SLACK_WEBHOOK_URL")
    if not url:
        return False

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=10.0) as resp:
            return resp.status == 200
    except (urllib.error.URLError, Exception):
        return False


def submit_feedback(
    feedback_text: str,
    *,
    user_email: Optional[str] = None,
    user_name: Optional[str] = None,
    category: str = "General Feedback",
    webhook_url: Optional[str] = None,
) -> bool:
    """Submit user feedback, feature suggestions, or issue reports directly to the RedoxQuant Slack channel.

    Parameters
    ----------
    feedback_text:
        The feedback, question, or issue description from the user.
    user_email:
        Optional contact email for follow-up (e.g. 'scientist@pharma.com').
    user_name:
        Optional name or lab identifier.
    category:
        Category tag ('Feature Request', 'Bug Report', 'General Feedback', 'ML Discussion').
    webhook_url:
        Optional Slack webhook URL override; defaults to REDOXQUANT_FEEDBACK_WEBHOOK or SLACK_WEBHOOK_URL env vars.


    Returns
    -------
    bool
        True if feedback was submitted successfully.
    """
    url = (
        webhook_url
        or os.environ.get("REDOXQUANT_FEEDBACK_WEBHOOK")
        or os.environ.get("REDOXQUANT_SLACK_WEBHOOK")
        or os.environ.get("SLACK_WEBHOOK_URL")
    )
    if not url:
        return False

    blocks: List[Dict[str, Any]] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"📬 RedoxQuant Feedback: {category}", "emoji": True},
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*{feedback_text}*"},
        },
    ]


    fields: List[Dict[str, str]] = []
    if user_name:
        fields.append({"type": "mrkdwn", "text": f"*User:*\n{user_name}"})
    if user_email:
        fields.append({"type": "mrkdwn", "text": f"*Contact:*\n`{user_email}`"})
    fields.append({"type": "mrkdwn", "text": f"*Category:*\n{category}"})

    blocks.append({"type": "section", "fields": fields})
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "Direct Developer Channel: *<mailto:support@yaylali.uk|support@yaylali.uk>* | *Kemal Yaylalı*",
            }
        ],
    })

    payload = {"blocks": blocks}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=10.0) as resp:
            return resp.status == 200
    except (urllib.error.URLError, Exception):
        return False


